---
- hosts: datacenter
  connection: local
  gather_facts : no

  tasks:
    - name: "Save configuration and reload"
      dellos10_command:
        commands:
          - write memory
#          - reload
        provider: "{{ cli }}"

